apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: dotnet-app-20
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: dotnet-app-20
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/kadourah/dotnetapp20
      ref:
        branch: main
